import { createSlice, PayloadAction, EntityState } from "@reduxjs/toolkit";
import type { AppDispatch, RootState } from '../../app/store';
import { SectorProps } from "../../components/PlayingField/Sector/SectorProps.model";
import { Sector } from "../../models/Sector.model";

interface PlayingFieldState {
    sectorList: Sector[];
}

const initialState: PlayingFieldState = {
    sectorList: [
        {
            title: 'Старт',
            price: 0,
            color: null,
            type: 'Старт',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Гапеева',
            price: 60,
            color: 'purple',
            type: 'Земельный участок',
            isBottom: false,
            owner: 0,
        },
        {
            title: 'Банк',
            price: 0,
            color: null,
            type: 'Банк',
            isBottom: false,
            owner: 1
        },
        {
            title: 'Кривогуза',
            price: 60,
            color: 'purple',
            type: 'Земельный участок',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Налог с дохода',
            price: 0,
            color: null,
            type: 'Ловушка',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Западный порт',
            price: 0,
            color: null,
            type: 'Транспортное предприятие',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Чкалова',
            price: 100,
            color: 'blue',
            type: 'Земельный участок',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Шанс',
            price: 0,
            color: null,
            type: 'Шанс',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Бухар Жирау',
            price: 100,
            color: 'blue',
            type: 'Земельный участок',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Пушкина',
            price: 120,
            color: 'blue',
            type: 'Земельный участок',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Тюрьма',
            price: 0,
            color: null,
            type: 'Ловушка',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Бульвар мира',
            price: 140,
            color: 'blue-sky',
            type: 'Земельный участок',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Электрическая компания',
            price: 0,
            color: null,
            type: 'Коммунальное предприятие',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Абая',
            price: 140,
            color: 'blue-sky',
            type: 'Земельный участок',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Гоголя',
            price: 160,
            color: 'blue-sky',
            type: 'Земельный участок',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Северный порт',
            price: 0,
            color: null,
            type: 'Транспортное предприятие',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Ержанова',
            price: 180,
            color: 'green',
            type: 'Земельный участок',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Банк',
            price: 0,
            color: null,
            type: 'Банк',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Ермекова',
            price: 180,
            color: 'green',
            type: 'Земельный участок',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Абдирова',
            price: 200,
            color: 'green',
            type: 'Земельный участок',
            isBottom: false,
            owner: null,
        },
        {
            title: 'Гостиничный комплекс',
            price: 400,
            color: 'pink',
            type: 'Земельный участок',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Дорогая покупка',
            price: 0,
            color: null,
            type: 'Ловушка',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Курортная зона',
            price: 350,
            color: 'pink',
            type: 'Земельный участок',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Шанс',
            price: 0,
            color: null,
            type: 'Шанс',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Южный порт',
            price: 0,
            color: null,
            type: 'Транспортное предприятие',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Авиакомпания',
            price: 400,
            color: 'red',
            type: 'Земельный участок',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Банк',
            price: 0,
            color: null,
            type: 'Банк',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Железная дорога',
            price: 300,
            color: 'red',
            type: 'Земельный участок',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Морские перевозки',
            price: 300,
            color: 'red',
            type: 'Земельный участок',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Арест',
            price: 0,
            color: null,
            type: 'Ловушка',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Сотовая связь',
            price: 280,
            color: 'orange',
            type: 'Земельный участок',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Водопроводная компания',
            price: 400,
            color: null,
            type: 'Коммунальное предприятие',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Интернет',
            price: 260,
            color: 'orange',
            type: 'Земельный участок',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Компьютерная техника',
            price: 260,
            color: 'orange',
            type: 'Земельный участок',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Восточный порт',
            price: 0,
            color: null,
            type: 'Транспортное предприятие',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Ресторан',
            price: 240,
            color: 'yellow',
            type: 'Земельный участок',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Ночной клуб',
            price: 220,
            color: 'yellow',
            type: 'Земельный участок',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Шанс',
            price: 0,
            color: null,
            type: 'Шанс',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Бар',
            price: 220,
            color: 'yellow',
            type: 'Земельный участок',
            isBottom: true,
            owner: null,
        },
        {
            title: 'Бесплатная парковка',
            price: 0,
            color: null,
            type: 'Бесплатная парковка',
            isBottom: true,
            owner: null,
        },
    ],
};

export const playingFieldSlice = createSlice({
    name: 'playingField',
    initialState,
    reducers: {},
});

export const selectTopLineSectors = (state: RootState) => { 
    return state.field.sectorList.filter(({ isBottom }) => !isBottom);
};
export const selectBottomLineSectors = (state: RootState) => { 
    return state.field.sectorList.filter(({ isBottom }) => isBottom);
};

export default playingFieldSlice.reducer;
